{% set name = "maestrowf" %}
{% set version = "1.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LLNL/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ea7ae54bdeeb4639fd7cd1e211b71dafac20d26005def54de7f175945d747003

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python
  entry_points:
    - maestro = maestrowf.maestrowf:main
    - conductor = maestrowf.conductor:main

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - coloredlogs
    - dill
    - filelock
    - importlib_metadata
    - jsonschema >=3.2.0
    - packaging >=22.0
    - pyyaml >=4.2.b1
    - rich
    - six
    - tabulate

test:
  imports:
    - maestrowf
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/LLNL/maestrowf
  summary: 'Orchestration Tool'
  description: |
    Bring rigor, reproducibility, and shareability to your computational science following the model set by the experimental disciplines. Specify computational processes in a generalized way such that they can be documented, shared, executed, and easily reproduced
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://maestrowf.readthedocs.io/
  dev_url: https://github.com/llnl/maestrowf/

extra:
  recipe-maintainers:
    - jwhite242
    - doutriaux1
    - FrankD412
    - bgunnar5
